src/ClientProject/Controllers/EmployeesManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClientProject.Data;
using ClientProject.Models;
using Microsoft.AspNetCore.Identity;
using ClientProject.Services;
using Microsoft.Extensions.Logging;
using ClientProject.Models.EmployeesManagementViewModels;
using System.Diagnostics;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace ClientProject.Controllers
{
    public class EmployeesManagementController : Controller
    {
        private readonly UserManager<Employee> _userManager;
        private readonly SignInManager<Employee> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;
        private readonly ISmsSender _smsSender;
        
        public EmployeesManagementController(
            UserManager<Employee> userManager,
            SignInManager<Employee> signInManager,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext context,
            IEmailSender emailSender,
            ISmsSender smsSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
            _context = context;
            _emailSender = emailSender;
            _smsSender = smsSender;
        }

        //
        // GET: /EmployeesManagement
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/Index")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        //
        // GET: /EmployeesManagement/Create
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/Create")]
        public IActionResult Create()
        {
            return View();
        }

        //
        // POST: /EmployeesManagement/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/Create")]
        public async Task<IActionResult> Create(CreateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var employee = new Employee { UserName = model.UserName, Email = model.Email, FirstName = model.FirstName, LastName = model.LastName, Wallet = model.Wallet };
                var user = await _userManager.CreateAsync(employee, model.Password);
                
                if (user.Succeeded)
                {
                    IdentityRole role = new IdentityRole { Name = "Employe", NormalizedName = "EMPLOYE" };
                    bool roleExist = await _roleManager.RoleExistsAsync(role.NormalizedName);
                    if (!roleExist)
                    {
                        IdentityResult roleResult = await _roleManager.CreateAsync(role);
                        if (roleResult.Succeeded)
                            await _userManager.AddToRoleAsync(employee, role.Name);
                    }
                    else
                    {
                        await _userManager.AddToRoleAsync(employee, role.Name);
                    }

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=532713
                    // Send an email with this link
                    //var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    //var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: HttpContext.Request.Scheme);
                    //await _emailSender.SendEmailAsync(model.Email, "Confirm your account",
                    //    $"Please confirm your account by clicking this link: <a href='{callbackUrl}'>link</a>");
                    return RedirectToAction("Index");
                }
                AddErrors(user);
            }
            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: EmployeesManagement/Edit/5
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/Edit/{id?}")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.SingleOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        //
        // POST: EmployeesManagement/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/Edit/{id?}")]
        public async Task<IActionResult> Edit(string id, [Bind("Id,FirstName,LastName,UserName,Email")] Employee model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Employee employeeInDb = await _userManager.FindByIdAsync(id);
                    if (employeeInDb == null)
                    {
                        return NotFound();
                    }
                    employeeInDb.FirstName = model.FirstName;
                    employeeInDb.LastName = model.LastName;
                    employeeInDb.UserName = model.UserName;
                    employeeInDb.Email = model.Email;

                    await _userManager.UpdateAsync(employeeInDb);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(model.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }

        //
        // GET: EmployeesManagement/AddToWallet/5
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/AddToWallet/{id?}")]
        public async Task<IActionResult> AddToWallet(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Employee employee = await _userManager.FindByIdAsync(id);
            if (employee == null)
            {
                return NotFound();
            }

            AddToWalletViewModel model = new AddToWalletViewModel { Id = employee.Id, FirstName = employee.FirstName, LastName = employee.LastName, UserName = employee.UserName, Email = employee.Email, Wallet = employee.Wallet, AddToWallet = (decimal)0.00 };

            return View(model);
        }

        //
        // POST: EmployeesManagement/AddToWallet/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Responsable")]
        [Route("EmployeesManagement/AddToWallet/{id?}")]
        public async Task<IActionResult> AddToWallet(string id, AddToWalletViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                var employee = await _context.Employees.SingleOrDefaultAsync(m => m.Id == model.Id);
                if (employee == null)
                {
                    return NotFound();
                }

                if(employee.Wallet + model.AddToWallet >= 0)
                {
                    employee.Wallet += model.AddToWallet;

                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }

                return RedirectToAction("Index");
            }
            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: EmployeesManagement/Delete/5
        /*public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.SingleOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }*/

        //
        // POST: EmployeesManagement/Delete/5
        /*[HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var employee = await _context.Employees.SingleOrDefaultAsync(m => m.Id == id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }*/


        private void AddErrors(IdentityResult result)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
        }
        private bool EmployeeExists(string id)
        {

src/ClientProject/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using ClientProject.Models
@using ClientProject.Data;

@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientProject</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    @{ 
        Order cartOrder = ShoppingCart.GetCartContent(User, HttpContextAccessor.HttpContext);
    }
    <div class="modal fade" id="myCart" tabindex="-1" role="dialog" aria-labelledby="cartModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <p style="display:inline;">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <img src="~/images/ShoppingCartIcon.png" height="30px" width="30px" style="display: inline;" />
                        <h4 class="modal-title" id="cartModalLabel" style="display: inline;">Panier</h4>
                    </p>
                </div>
                <div class="modal-body">
                    
                    @if (cartOrder.OrderLines.Count == 0)
                    {
                        @:Votre panier est vide.
                    }
                    else
                    {
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(m => cartOrder.OrderLines.First().Quantity)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(m => cartOrder.OrderLines.First().Sandwich)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(m => cartOrder.OrderLines.First().OrderLineVegetables)
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @{ var line = 0; }
                                @foreach (var orderLine in cartOrder.OrderLines)
                                {
                                    String vegetablesListDisplay = "";
                                    if (orderLine.OrderLineVegetables.Count != 0)
                                    {
                                        for (var i = 0; i < orderLine.OrderLineVegetables.Count-1; i++)
                                        {
                                            vegetablesListDisplay += orderLine.OrderLineVegetables.ElementAt(i).Vegetable.Name + ", ";
                                        }
                                        vegetablesListDisplay += orderLine.OrderLineVegetables.ElementAt(orderLine.OrderLineVegetables.Count - 1).Vegetable.Name;
                                    }
                                
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(mItem => orderLine.Quantity)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(mItem => orderLine.Sandwich.Name)
                                        </td>
                                        <td>
                                            @vegetablesListDisplay
                                        </td>
                                        <td>
                                            <a asp-controller="Menu" asp-action="SuppLineCart" asp-route-id=line><button type="button" class="btn btn-danger btn-xs">X</button></a>
                                        </td>
                                    </tr>
                                    line++;
                                }
                            </tbody>
                        </table>
                        <p><b>@Html.DisplayNameFor(mItem => cartOrder.TotalAmount) : </b>@Html.DisplayFor(mItem => cartOrder.TotalAmount) €</p>
                    }
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
                    <a asp-controller="Menu" asp-action="InvalidateCartSession"><button type="button" class="btn btn-danger">Vider le panier</button></a>
                    <a asp-controller="Menu" asp-action="ValidateSessionCart"><button type="button" class="btn btn-primary">Passer la commande</button></a>
                </div>
            </div>
        </div>
    </div>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Sandwicherie</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Menu" asp-action="Index">Carte du snack</a></li>
                    @if (User != null)
                    {
                        var user = await UserManager.GetUserAsync(User);
                        @if (user != null && await UserManager.IsInRoleAsync(user, "Responsable"))
                        {
                        <li><a asp-area="" asp-controller="EmployeesManagement" asp-action="Index">Gestion des employés</a></li>
                        }
                    }
                    @*<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>*@
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - ClientProject</p>
        </footer>
    </div>

    
    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>